"""Recreate tables after drop_all

Revision ID: 6628430a64bb
Revises: 47f4db850cca
Create Date: 2025-10-07 19:05:56.889646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6628430a64bb'
down_revision = '47f4db850cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preacher', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('time_stamp', sa.String(length=15), nullable=False),
    sa.Column('original_filename', sa.String(length=50), nullable=False),
    sa.Column('filepath', sa.String(length=50), nullable=False),
    sa.Column('storage_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=320), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_storage')
    op.drop_table('reset_token')
    op.drop_table('user')
    op.drop_table('audio_storage')
    # ### end Alembic commands ###
