"""Initial migration

Revision ID: 82567183cee2
Revises: 
Create Date: 2025-09-29 21:16:52.281926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82567183cee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('session_storage_User_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('User_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('session_storage_User_id_fkey'), 'user', ['User_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
